### ISSUE TITLE
Add php8.2 in require section

### ISSUE THREAD

**Issue by amazur-ext** [ho-nl/magento2-Ho_Templatehints#65]
https://github.com/ho-nl/magento2-Ho_Templatehints/blob/d62ba3d93106a766f5509f524bef7b0faa2858ba/composer.json#L15

**Comment by vncnt-mb** [comment]
Yeah, Composer refuse to update because PHP 8.2 is not on the require section
<img width="1114" alt="Capture d’écran 2023-07-25 à 14 38 13" src="https://github.com/ho-nl/magento2-Ho_Templatehints/assets/48125944/f0317175-579f-4833-af27-1d13eb961287">

It is possible to update `composer.json`? Many thanks ! Your module is great for inspection debugging 😄

**Comment by PascalBrouwers** [comment]
@amazur-ext @vncnt-mb support for PHP 8.2 has been added.
